setup:
    data:
        source: "/input/dir/here"
        type: "local"
    output_dir: "/output/dir/here"
    processes: 1
    mode: "dpo"

processing:
    huggingface_tokenizer: <hf_tokenizer>
    max_seq_length: <max_seq_length>

    write_in_batch: True
    resume_from_checkpoint: False

    read_hook: "cerebras.modelzoo.data_preparation.data_preprocessing.hooks:dpo_read_hook"
    read_hook_kwargs:
        data_keys:
            prompt_key: <prompt_key>
            chosen_key: <chosen_key>
            rejected_key: <rejected_key>
    shuffle_seed: 0
    shuffle: False

dataset:
    use_ftfy: True
    ftfy_normalizer: "NFC"
    wikitext_detokenize: False
