setup:
    data:
        source: "/input/dir/here"
        type: "local"
    output_dir: "/output/dir/here"
    processes: 1
    mode: "pretraining"

processing:
    huggingface_tokenizer: "tiiuae/falcon-7b"
    max_seq_length: 2048
    short_seq_prob: 0.0

    write_in_batch: True

    resume_from_checkpoint: False
    seed: 0

    read_hook: "cerebras.modelzoo.data_preparation.data_preprocessing.hooks:text_read_hook"
    read_hook_kwargs:
        data_keys:
            text_key: "text"

dataset:
    use_ftfy: True
    ftfy_normalizer: "NFC"
    wikitext_detokenize: False

    pack_sequences: True
