setup:
    data:
        source: "/path/to/your/data"
        type: "local"
    output_dir: "/path/to/output/dir"
    processes: 1
    mode: "finetuning"

processing:
    huggingface_tokenizer: "NousResearch/Llama-2-7b-hf"
    max_seq_length: 4096

    write_in_batch: True

    resume_from_checkpoint: False

    read_hook: "cerebras.modelzoo.data_preparation.data_preprocessing.hooks:chat_read_hook"
    read_hook_kwargs:
        data_keys:
            multi_turn_key: "messages"
            multi_turn_content_key: "content"

    shuffle_seed: 0
    shuffle: False

dataset:
    use_ftfy: True
    ftfy_normalizer: "NFC"
    wikitext_detokenize: False

