# GPT-J 6B model

train_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: "./input/pile_pretraining_gpt/train_msl2048/"
    vocab_size: 50400
    max_sequence_length: 2048
    shuffle: True
    repeat: True
    batch_size: 65

eval_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: "./input/pile_pretraining_gpt/val_msl2048/"
    vocab_size: 50400
    max_sequence_length: 2048
    shuffle: True
    repeat: False
    batch_size: 65

model:
    share_embedding_weights: True
    max_position_embeddings: 2048

    hidden_size: 4096
    num_heads: 16
    num_hidden_layers: 28

    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    use_ffn_bias: True

    filter_size: 16384
    nonlinearity: "gelu"

    rotary_dim: 64
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: True

    embedding_initializer:
        - name: "scaled_init_normal"
          key: "vocab_size"

    initializer:
        - name: "variance_scaling"
          scale: 1.0

    output_layer_initializer:
        - name: "variance_scaling"
          scale_type: "wang_init"

    mixed_precision: True
    boundary_casting: False
    tf_summary: False

optimizer:
    optimizer_type: "adamw"
    epsilon: 1.0e-6
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    use_bias_correction: True
    max_loss_scale: 4290774016.0
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 4.3e-5
          steps: 23630 # approx 1.5M samples
        - scheduler: "Cosine"
          initial_learning_rate: 4.3e-5
          alpha: 0.1
          decay_steps: 2363000 # approx 150M samples
        - scheduler: "Constant"
          learning_rate: 4.3e-6
    loss_scaling_factor: "dynamic"  # Change to "tf_dynamic" on GPU
    log_summaries: True

runconfig:
    max_steps: 2700000 # approx 175M samples
    save_summary_steps: 500
    save_checkpoints_steps: 5000
    keep_checkpoint_max: 2
    enable_distributed: False
