# LLaMa v3.1 model, 8B parameters, max_seq_length 8192

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./llama_v3_dataset_vocab128256/train"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 960
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    micro_batch_size: 20
    # SDR micro_batch_size: 18
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./michaelw/mle_datasets/rpj_1t/rpj_1t_100k_llama3p1_msl8k_val"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 960
    micro_batch_size: 20
    shuffle: false
    num_workers: 8

model:
    # Embedding
    vocab_size: 128256
    hidden_size: 4096
    position_embedding_type: "rotary"
    rope_theta: 500000.0
    rotary_dim: 128
    share_embedding_weights: false
    max_position_embeddings: 8192
    embedding_dropout_rate: 0.0
    embedding_layer_norm: false

    pos_scaling_extra_args:
        high_freq_factor: 4.0
        low_freq_factor: 1.0
        original_max_position_embeddings: 8192
    pos_scaling_factor: 8.0
    pos_scaling_type: llama3

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_module: "multiquery_attention"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: false
    use_ffn_bias_in_attention: false
    extra_attention_params:
        num_kv_groups: 8

    # Decoder - ffn
    filter_size: 14336
    nonlinearity: "swiglu"
    use_ffn_bias: false

    # Task-specific
    use_bias_in_output: false
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Initializer
    initializer_range: 0.02

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer:
    optimizer_type: "Adam"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
      - scheduler: "CosineDecay"
        initial_learning_rate: 0
        end_learning_rate: 3.0e-5  
        total_iters: 150
      - scheduler: "CosineDecay"
        initial_learning_rate: 3.0e-5  
        end_learning_rate: 3.0e-6
        total_iters: 1500        
    max_gradient_norm: 1.0
    log_summaries: True
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 4768 #20B tokens, max_steps = 20e9/(8192*512)
    log_steps: 1
    save_initial_checkpoint: False
    checkpoint_steps: 132 # every epoch
    load_checkpoint_states: model
    disable_strict_checkpoint_loading: True
    seed: 1
    eval_steps: 2
    compile_crd_memory_gi: 67
    execute_crd_memory_gi: 50
