trainer:
  init:
    model_dir: ./model_dir
    seed: 1
    model:
      attention_dropout_rate: 0.0
      disable_nsp: true
      dropout_rate: 0.0
      embedding_layer_norm: false
      encoder_nonlinearity: gelu
      filter_size: 10240
      hidden_size: 2560
      initializer_range: 0.02
      layer_norm_epsilon: 1.0e-05
      mask_token_id: 32
      max_position_embeddings: 1026
      mixed_precision: true
      mlm_nonlinearity: gelu
      mlm_loss_weight: 0.0256
      num_heads: 40
      num_hidden_layers: 36
      pad_token_id: 1
      position_embedding_type: rotary
      rotary_dim: 64
      share_embedding_weights: true
      token_dropout: true
      use_final_layer_norm: true
      fp16_type: cbfloat16
      vocab_size: 33
    optimizer:
      Adam:
        betas:
        - 0.9
        - 0.98
        eps: 1.0e-08
        weight_decay: 0.01
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 2.5e-06
            total_iters: 30000
        - LinearLR:
            initial_learning_rate: 2.5e-06
            end_learning_rate: 2.5e-07
            total_iters: 6200000
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      steps_per_increase: 30000
      log_loss_scale: true
    loop:
      max_steps: 32000
    checkpoint:
      steps: 32000
    logging:
      log_steps: 100
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 135
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 90
    - ComputeNorm: {}
    - LoadCheckpointStates:
        load_checkpoint_states: model
  fit:
    train_dataloader:
      data_processor: BertCSVDataProcessor
      data_dir: ./language/datasets/esm2/train/
      batch_size: 135
      shuffle: true
      shuffle_seed: 1
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader: &id001
      data_processor: BertCSVDataProcessor
      data_dir: ./language/datasets/esm2/validation/
      batch_size: 450
      shuffle: true
      shuffle_seed: 1
      num_workers: 3
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders: *id001
