# ESM-2 Model, 150M parameters, max_seq_length 1026
# Based on: https://huggingface.co/facebook/esm2_t30_150M_UR50D


train_input:
    data_processor: "BertHDF5DataProcessor"
    data_dir: "./language/datasets/scratch/esm2/non_vsl"
    shuffle: False
    shuffle_seed: 1
    batch_size: 2048
    num_workers: 0
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertCSVDataProcessor"
    data_dir: "./language/datasets/esm2/validation/"
    shuffle: False
    shuffle_seed: 1
    batch_size: 2048
    num_workers: 0
    prefetch_factor: 10
    persistent_workers: True

model:
    attention_dropout_rate: 0.0
    disable_nsp: true
    dropout_rate: 0.0
    embedding_layer_norm: false
    encoder_nonlinearity: gelu
    filter_size: 2560
    hidden_size: 640
    initializer_range: 0.02
    layer_norm_epsilon: 1.0e-05
    mask_token_id: 32
    max_position_embeddings: 1026
    mixed_precision: true
    mlm_nonlinearity: gelu
    mlm_loss_weight: 0.0256 # = 1/(0.15/4 * 1026). The synthetic data processor
                            # masks 15% /4 of the sequence on average.
    num_heads: 20
    num_hidden_layers: 30
    pad_token_id: 1
    position_embedding_type: rotary
    rotary_dim: 32
    share_embedding_weights: true
    token_dropout: true
    use_final_layer_norm: true
    fp16_type: "cbfloat16"
    vocab_size: 33

optimizer:
    optimizer_type: "Adam"
    betas: [0.9, 0.98]
    eps: 1.0e-8
    weight_decay: 0.01
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 4.0e-4
          total_iters: 2000
        - scheduler: "Linear"
          initial_learning_rate: 4.0e-4
          end_learning_rate: 4.0e-5
          total_iters: 450000
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 500000
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 233
