# A 13B parameter Cerebras-GPT model configuration intended to run on a cluster
# of 12 CS-2s

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/"
    max_sequence_length: 2048
    repeat: True
    shuffle: True
    shuffle_seed: 0
    batch_size: 90 # 1080 global = (90 micro)*(12-box)*(1 grad accum steps)
    vocab_size: 50257
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 120
    repeat: False
    shuffle: False
    num_workers: 1


### Model
model:
    # Embedding
    hidden_size: 5120
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048
    vocab_size: 50257

    # Encoder
    num_hidden_layers: 40
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training


    # Encoder - Attention
    num_heads: 40
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 20480
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
    initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
    output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.0025
        a: -0.005
        b: 0.005

    # Task-specific
    # loss_scaling defaults to num_tokens
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True
    use_bfloat16: True
    precision_opt_level: 0

### Optimization
optimizer:
    optimizer_type: "AdamW"
    beta1: 0.9
    beta2: 0.95
    eps: 1.0e-9
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.00012
        steps: 169
      - scheduler: "CosineDecay"
        initial_learning_rate: 0.00012
        end_learning_rate: 1.2000e-05
        steps: 116054
    weight_decay_rate: 0.1
    log_summaries: True
    correct_bias: True

### Cerebras parameters
runconfig:
    max_steps: 116223
    eval_steps: 1507 # 180956 / 120
    checkpoint_steps: 500
    save_summary_steps: 1
    enable_distributed: False
    save_losses: True
    log_steps: 1
    save_initial_checkpoint: False
    use_appliance_data: True
    execution_strategy: "weight_streaming"
