# Gemma2 model, 27B parameters, max_seq_length 8192

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./michaelw/mle_datasets/wiki_en_100k_gemma2_msl8k_train/" # Colo
    num_examples: 10000
    vocab_size: 256000
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./michaelw/mle_datasets/wiki_en_10k_gemma2_msl8k_val/" # Colo
    num_examples: 10000
    vocab_size: 256000
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    shuffle: false
    num_workers: 8


model:
    attention_dropout_rate: 0.0
    attention_inner_dim: 4096
    attention_logit_softcapping: 50.0
    attention_logits_alpha: 0.9428090415820634
    attention_module: multiquery_attention
    attention_sliding_window_length: 4096
    dropout_rate: 0.0
    embeddings_scale: 67.8822509
    extra_attention_params:
        num_kv_groups: 16
    filter_size: 36864
    final_logit_softcapping: 30.0
    hidden_size: 4608
    layer_norm_epsilon: 1.0e-06
    max_position_embeddings: 8192
    mixed_precision: true
    norm_first_sandwich: true
    nonlinearity: geglu
    norm_type: rmsnorm
    num_heads: 32
    num_hidden_layers: 46
    position_embedding_type: rotary
    rope_theta: 10000.0
    rotary_dim: 128
    share_embedding_weights: true
    sliding_window_every_other_decoder_layer: true
    use_ffn_bias_in_attention: false
    use_projection_bias_in_attention: false
    use_ffn_bias: false
    vocab_size: 256000

# TODO: Optimizer & Runconfig params copied from llama3
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "CosineDecay"
          initial_learning_rate: 0
          end_learning_rate: 5.0e-5  
          total_iters: 10
        - scheduler: "CosineDecay"
          initial_learning_rate: 5.0e-5  
          end_learning_rate: 5.0e-6
          total_iters: 160
    max_gradient_norm: 1.0
    log_summaries: True
    loss_scaling_factor: "dynamic"

runconfig:
    # loss valid tokens: 110784565; max_steps = 110784565/(8192*80)
    max_steps: 170 
    checkpoint_steps: 85
    log_steps: 1
    save_initial_checkpoint: False
    load_checkpoint_states: model
    disable_strict_checkpoint_loading: True
    seed: 1
    # loss valid tokens: 9828790; eval_steps = 9828790 / (8192*80)
    eval_steps: 15 
