# Mixtral model, 8x22B parameters, max_seq_length 65536
# Based on: https://huggingface.co/mistral-community/Mixtral-8x22B-v0.1
train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./datasets/long_msl/shuffled/mistral/msl_64k"
    vocab_size: 32000
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    # batch size changes from 256 -> 12 for shorter test runtime.
    batch_size: 12
    micro_batch_size: 1
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./datasets/long_msl/shuffled/mistral/msl_64k"
    vocab_size: 32000
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    micro_batch_size: 1
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 32000
    hidden_size: 6144
    position_embedding_type: "rotary"
    rotary_dim: 128
    rope_theta: 1000000.0
    share_embedding_weights: False
    max_position_embeddings: 65536
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 56
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 48
    attention_type: "scaled_dot_product"
    attention_module: "multiquery_attention"
    extra_attention_params:
        num_kv_groups: 8
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 16384
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # MoE - ffn
    moe:
        num_experts: 8
        top_k: 2
        load_balancing_loss_coef: 0.001
        router_fp32: True

    # Task-specific
    use_bias_in_output: False

    # Cerebras parameters
    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.0e-4
          total_iters: 2000
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.0e-4
          end_learning_rate: 3.0e-5
          total_iters: 236418
    max_gradient_norm: 1.0
    loss_scaling_factor: "dynamic"

runconfig:
    # Note that Mixtral training details are not released currently 
    # We might want to adjust these later 
    max_steps: 238418
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 233
    num_workers_per_csx: 1
    num_wgt_servers: 24
    execute_crd_memory_gi: 50
