# Falcon model, 7B parameters, MSL 2048
# Based on: https://huggingface.co/tiiuae/falcon-7b/tree/main

# NOTE:
# The only minor difference is that falcon tie dropout between mlp and attention_output
# on our implementation this is untied (2 dropouts)
# however, in the pretrained falcon model all dropout rates are set to be 0.0 so it is equivalent

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./falcon_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 16
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./falcon_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 16
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 65024
    position_embedding_type: "rotary"
    rotary_dim: 64 # hidden_size / num_heads, falcon use 100% rotation, reference: https://huggingface.co/tiiuae/falcon-7b-instruct/blob/main/modelling_RW.py#L59
    embedding_dropout_rate: 0.0
    share_embedding_weights: True # no config default values, HF uses tie_weights as default

    # Decoder Block
    hidden_size: 4544
    filter_size: 18176
    num_heads: 71
    num_hidden_layers: 32
    max_position_embeddings: 2048
    attention_module: "multiquery_attention"
    attention_type: "scaled_dot_product"
    use_untied_layer_norm: False
    extra_attention_params:
        num_kv_groups: 1

    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    use_ffn_bias: False

    nonlinearity: "gelu"
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.0

    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    loss_scaling: "batch_size"
    loss_weight: 0.00048828125

    # initialization of falcon based on HF repo is all normal with mean = 0.0 & std=0.02
    # reference: https://huggingface.co/tiiuae/falcon-7b-instruct/blob/main/modelling_RW.py#L434

    mixed_precision: True
    use_bfloat16: True
    precision_opt_level: 1
    dropout_rate: 0.0

optimizer:
    optimizer_type: "adamw"
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-8
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
    - steps: 13540 # 1% of max_steps
      scheduler: "Linear"
      initial_learning_rate: 0.0
      end_learning_rate: 6.0e-4
    - scheduler: "CosineDecay"
      initial_learning_rate: 6.0e-4
      steps: 5362037 # 5416198 - 54161
      end_learning_rate: 1.2e-5 # (1 - 0.9) * 4.9e-5

runconfig:
    max_steps: 5416198 # 320000 * 512 / 121
    log_steps: 100
    checkpoint_steps: 5000
    use_cs_grad_accum: True
    seed: 1
