# ESM-2 Model, 150M parameters + 1026 MSL (fits on A10 GPU), deterministic
# Based on: https://huggingface.co/facebook/esm2_t30_150M_UR50D

train_input:
    data_processor: "BertCSVDataProcessor"
    data_dir: "/cb/datasets/language/esm2/finetune/deeploc2-data/train"
    batch_size: 4
    micro_batch_size: 4
    shuffle: True
    shuffle_seed: 1
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertCSVDataProcessor"
    data_dir: "/cb/datasets/language/esm2/finetune/deeploc2-data/test"
    batch_size: 4
    micro_batch_size: 4
    shuffle: True
    shuffle_seed: 1
    prefetch_factor: 10
    persistent_workers: True

model:
    attention_dropout_rate: 0.0
    disable_nsp: true
    dropout_rate: 0.0
    embedding_layer_norm: false
    encoder_nonlinearity: gelu
    filter_size: 2560
    hidden_size: 640
    initializer_range: 0.02
    layer_norm_epsilon: 1.0e-05
    mask_token_id: 32
    max_position_embeddings: 1026
    mixed_precision: true
    num_heads: 20
    num_hidden_layers: 30
    pad_token_id: 1
    position_embedding_type: rotary
    rotary_dim: 32
    share_embedding_weights: true
    token_dropout: true
    use_final_layer_norm: true
    fp16_type: "cbfloat16"
    vocab_size: 33
    num_labels: 2
    freeze_pretrained_model: False
    compute_eval_metrics: True
    classifier_dropout: 0.4

optimizer:
    optimizer_type: "Adam"
    betas: [0.9, 0.98]
    eps: 1.0e-8
    weight_decay: 0.01
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 1.0e-5
          total_iters: 500
        - scheduler: "Linear"
          initial_learning_rate: 1.0e-5
          end_learning_rate: 1.0e-6
          total_iters: 4500
        - scheduler: "Linear"
          initial_learning_rate: 1.0e-6
          end_learning_rate: 4.0e-7
          total_iters: 15000
    loss_scaling_factor: "dynamic"
    log_summaries: True

runconfig:
    num_epochs: 6
    log_steps: 1
    checkpoint_steps: 100
    eval_frequency: 100
    eval_steps: 10
    seed: 1
    model_dir: "./model_dir"
    disable_strict_checkpoint_loading: True
    num_act_servers: 1
    #save_initial_checkpoint: True
    # use this line when loading CSX checkpoint on GPU
    #load_checkpoint_states: model